//Creating new account
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//user login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

//setting/saving the account macros
// export const SAVE_USER_MACROS_REQUEST = 'SAVE_USER_MACROS_REQUEST';
// export const SAVE_USER_MACROS_SUCCESS = 'SAVE_USER_MACROS_SUCCESS';
// export const SAVE_USER_MACROS_FAIL = 'SAVE_USER_MACROS_FAIL';

//setting/saving the account weight
// export const SAVE_USER_WEIGHT_REQUEST = 'SAVE_USER_WEIGHT_REQUEST';
// export const SAVE_USER_WEIGHT_SUCCESS = 'SAVE_USER_WEIGHT_SUCCESS';
// export const SAVE_USER_WEIGHT_FAIL = 'SAVE_USER_WEIGHT_FAIL';

//update user detail in general
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET';

//get account details
export const GET_ACCOUNT_DETAILS_REQUEST = 'GET_ACCOUNT_DETAILS_REQUEST';
export const GET_ACCOUNT_DETAILS_SUCCESS = 'GET_ACCOUNT_DETAILS_SUCCESS';
export const GET_ACCOUNT_DETAILS_FAIL = 'GET_ACCOUNT_DETAILS_FAIL';